#   @b Project: Wump
#   @file        cxxtest.mk
#   @author      Szymon Gutaj
#   @brief       Makefile for building cxxtest
#   @date        10-04-2011
#   @version     0.1
#   @b History:
#    - 30-03-2011
#      - sgutaj
#        - Initial creation

ifeq ($(UNIT_TESTS),Yes)

# Initialize internal variables -----------------------------------------------#

# Input directory
TESTS_DIR_CXXTEST:=$(TESTS_DIR_FRAMEWORKS)/cxxtest
TESTS_DIR_CXXTEST_EXTRA:=$(TESTS_DIR_FRAMEWORKS)/cxxtest_extra
TESTS_DIR_UOAM_TESTS_CXXTEST:=$(TESTS_DIR_UOAM_TESTS)/cxxtest

# Output directory
TESTS_DIR_CXXTEST_OUT:=$(TESTS_DIR_OUT)/$(TESTS_DIR_CXXTEST)

TESTS_DIR_UOAM_TESTS_CXXTEST_OUT:=$(TESTS_DIR_OUT)/$(TESTS_DIR_UOAM_TESTS_CXXTEST)

# Sources
TESTS_SRC_CXXTEST_EXTRA:=$(wildcard $(TESTS_DIR_CXXTEST_EXTRA)/*$(TESTS_EXT_SRC))
TESTS_OBJ_CXXTEST_EXTRA:=$(subst $(TESTS_EXT_SRC),$(TESTS_EXT_OBJ),$(subst $(TESTS_DIR_CXXTEST_EXTRA),$(TESTS_DIR_CXXTEST_OUT),$(TESTS_SRC_CXXTEST_EXTRA)))
TESTS_DEP_CXXTEST_EXTRA:=$(subst $(TESTS_EXT_OBJ),$(TESTS_EXT_DEP),$(TESTS_OBJ_CXXTEST_EXTRA))
TESTS_HCK_CXXTEST_EXTRA:=$(call TESTS_CXXHACKS_DEFINE,$(TESTS_DIR_LIBRARY)/hack_cxxtest_extra$(TESTS_EXT_CXXHACKS))

TESTS_HDR_CXXTEST_GENERATED_TESTS:=$(TESTS_DIR_CXXTEST_OUT)/cxxtest_generated_tests$(TESTS_EXT_HDR)

# Unit tests
TESTS_HDR_UOAM_TESTS_CXXTEST:=$(TESTS_DIR_CXXTEST_EXTRA)/DeltaTest.h# Dummy test to satisfy the testgen.py script
TESTS_HDR_UOAM_TESTS_CXXTEST+=$(wildcard $(TESTS_DIR_UOAM_TESTS_CXXTEST)/*$(TESTS_EXT_HDR))
TESTS_HDR_UOAM_TESTS_CXXTEST+=$(wildcard $(TESTS_DIR_UOAM_TESTS_CXXTEST)/**/*$(TESTS_EXT_HDR))
TESTS_HDR_UOAM_TESTS_CXXTEST+=$(wildcard $(TESTS_DIR_UOAM_TESTS_CXXTEST)/**/**/*$(TESTS_EXT_HDR))
TESTS_HDR_UOAM_TESTS_CXXTEST+=$(wildcard $(TESTS_DIR_UOAM_TESTS_CXXTEST)/**/**/**/*$(TESTS_EXT_HDR))
TESTS_HDR_UOAM_TESTS_CXXTEST+=$(wildcard $(TESTS_DIR_UOAM_TESTS_CXXTEST)/**/**/**/**/*$(TESTS_EXT_HDR))
TESTS_HDR_UOAM_TESTS_CXXTEST+=$(wildcard $(TESTS_DIR_UOAM_TESTS_CXXTEST)/**/**/**/**/**/*$(TESTS_EXT_HDR))

# Other sources
TESTS_SRC_UOAM_TESTS_CXXTEST:=$(wildcard $(TESTS_DIR_UOAM_TESTS_CXXTEST)/*$(TESTS_EXT_SRC))
TESTS_SRC_UOAM_TESTS_CXXTEST+=$(wildcard $(TESTS_DIR_UOAM_TESTS_CXXTEST)/**/*$(TESTS_EXT_SRC))
TESTS_SRC_UOAM_TESTS_CXXTEST+=$(wildcard $(TESTS_DIR_UOAM_TESTS_CXXTEST)/**/**/*$(TESTS_EXT_SRC))
TESTS_SRC_UOAM_TESTS_CXXTEST+=$(wildcard $(TESTS_DIR_UOAM_TESTS_CXXTEST)/**/**/**/*$(TESTS_EXT_SRC))
TESTS_SRC_UOAM_TESTS_CXXTEST+=$(wildcard $(TESTS_DIR_UOAM_TESTS_CXXTEST)/**/**/**/**/*$(TESTS_EXT_SRC))
TESTS_SRC_UOAM_TESTS_CXXTEST+=$(wildcard $(TESTS_DIR_UOAM_TESTS_CXXTEST)/**/**/**/**/**/*$(TESTS_EXT_SRC))

TESTS_OBJ_UOAM_TESTS_CXXTEST:=$(subst $(TESTS_EXT_SRC),$(TESTS_EXT_OBJ),$(addprefix $(TESTS_DIR_OUT)/,$(TESTS_SRC_UOAM_TESTS_CXXTEST)))
TESTS_DEP_UOAM_TESTS_CXXTEST:=$(subst $(TESTS_EXT_OBJ),$(TESTS_EXT_DEP),$(TESTS_OBJ_UOAM_TESTS_CXXTEST))

# Append objects to global dependency list
TESTS_OUT_CONTENTS+=$(TESTS_OBJ_CXXTEST_EXTRA)
TESTS_OUT_CONTENTS+=$(TESTS_OBJ_UOAM_TESTS_CXXTEST)

TESTS_OUT_PREREQUISITES+=$(TESTS_HCK_CXXTEST_EXTRA)

# Cxxtest-specific flags
TESTS_CXXTEST_CPPFLAGS+=-I$(TESTS_DIR_CXXTEST) -I$(TESTS_DIR_CXXTEST_OUT) -DCXXUNIT
TESTS_CXXTEST_CXXFLAGS+=$(TESTS_IGNORE_4191)

# Rules -----------------------------------------------------------------------#
# Extras
$(TESTS_OBJ_CXXTEST_EXTRA): $(TESTS_DIR_CXXTEST_OUT)/%$(TESTS_EXT_OBJ): $(TESTS_DIR_CXXTEST_OUT)/%$(TESTS_EXT_DEP)
	$(TESTS_VAR_VERBOSE)\
    $(TESTS_CXX) -c $(TESTS_CPPFLAGS) $(TESTS_CXXFLAGS) \
    $(TESTS_CXXTEST_CPPFLAGS) \
    $(TESTS_CXXTEST_CXXFLAGS) \
    $(call TESTS_CXXHACKS_APPLY_1,$@) \
    $(TESTS_OPT_OBJ)$@ \
    $(TESTS_DIR_CXXTEST_EXTRA)/$*$(TESTS_EXT_SRC)

$(TESTS_HCK_CXXTEST_EXTRA): $(TESTS_OBJ_CXXTEST_EXTRA)
	$(TESTS_VAR_VERBOSE)\
    $(call TESTS_CXXHACKS_APPLY_2,$@,$^)

-include $(TESTS_DEP_CXXTEST_EXTRA)

$(TESTS_DEP_CXXTEST_EXTRA): $(TESTS_DIR_CXXTEST_OUT)/%$(TESTS_EXT_DEP): $(TESTS_DIR_CXXTEST_EXTRA)/%$(TESTS_EXT_SRC) \
                            $(TESTS_HDR_CXXTEST_GENERATED_TESTS)
	$(TESTS_VAR_VERBOSE)\
    $(TESTS_DEP) $(TESTS_CPPFLAGS) $(TESTS_DEPFLAGS) \
    $(TESTS_CXXTEST_CPPFLAGS) \
    $(TESTS_CXXTEST_CXXFLAGS) \
    $(TESTS_OPT_DEP)$@ \
    $(TESTS_DIR_CXXTEST_EXTRA)/$*$(TESTS_EXT_SRC)

# Generated tests
$(TESTS_HDR_CXXTEST_GENERATED_TESTS): $(TESTS_HDR_UOAM_TESTS_CXXTEST) | tests_directories_cxxtest
	$(TESTS_VAR_VERBOSE)\
    $(TESTS_PY) $(TESTS_DIR_CXXTEST)/cxxtestgen.py \
    -o $@ \
    $^

# Tests
$(TESTS_OBJ_UOAM_TESTS_CXXTEST): $(TESTS_DIR_UOAM_TESTS_CXXTEST_OUT)/%$(TESTS_EXT_OBJ): $(TESTS_DIR_UOAM_TESTS_CXXTEST_OUT)/%$(TESTS_EXT_DEP)
	$(TESTS_VAR_VERBOSE)\
    $(TESTS_CXX) -c $(TESTS_CPPFLAGS) $(TESTS_CXXFLAGS) \
    $(TESTS_CXXTEST_CPPFLAGS) \
    $(TESTS_CXXTEST_CXXFLAGS) \
    $(TESTS_OPT_OBJ)$@ \
    $(TESTS_DIR_UOAM_TESTS_CXXTEST)/$*$(TESTS_EXT_SRC)

-include $(TESTS_DEP_UOAM_TESTS_CXXTEST)

$(TESTS_DEP_UOAM_TESTS_CXXTEST): $(TESTS_DIR_UOAM_TESTS_CXXTEST_OUT)/%$(TESTS_EXT_DEP): $(TESTS_DIR_UOAM_TESTS_CXXTEST)/%$(TESTS_EXT_SRC) | tests_directories_cxxtest
	$(TESTS_VAR_VERBOSE)\
    $(TESTS_DEP) $(TESTS_CPPFLAGS) $(TESTS_DEPFLAGS) \
    $(TESTS_CXXTEST_CPPFLAGS) \
    $(TESTS_CXXTEST_CXXFLAGS) \
    $(TESTS_OPT_DEP)$@ \
    $(TESTS_DIR_UOAM_TESTS_CXXTEST)/$*$(TESTS_EXT_SRC)

# Output directories ----------------------------------------------------------#
.PHONY: tests_directories_cxxtest
# pragma runlocal
tests_directories_cxxtest:
	$(TESTS_VAR_VERBOSE)\
    $(call TESTS_CMD_MKDIR,$(sort $(dir $(TESTS_OBJ_CXXTEST_EXTRA) $(TESTS_OBJ_UOAM_TESTS_CXXTEST))))

endif # ifeq ($(UNIT_TESTS),Yes)
