xml_parser: middleware::xml::impl::xml_parser_basic< Context > Class Template Reference
middleware::xml::impl::xml_parser_basic< Context > Class Template Reference
#include <xml_parser_basic.h>
Classes
struct any
Process common XML bits.
struct attributes
Process attributes.
struct CDATA_section
Process CDATA section.
struct comment
Process comment.
struct content
Process content.
struct end_tag
Process end tag.
struct entity
Process entities.
struct processing_instruction
Process instruction.
struct root
Process root level of XML.
struct start_tag
Process start tag.
struct xml_declaration
Process XML declaration.
Public Member Functions
void parse (Context &context)
Private Types
enum status_t { ok, stay, err }
Internal status used in traversing.
typedef
xml_instruction_processor
< Context > instruction_processor
Static Private Member Functions
static void push_node (Context &c, xml_node_type::value_type const t, code_point const p)
static void pop_node (Context &c)
static void dump_name (Context &c)
static bool compare_name (Context &c)
static void clear_buffer (Context &c)
static void dump_value (Context &c)
static status_t input_malformed (Context &c, code_point rotten, xml_error_detail::value_type error_detail=xml_error_detail::no_details)
static status_t internal_error (Context &c, xml_error_detail::value_type error_detail)
Detailed Description
template<class Context>
class middleware::xml::impl::xml_parser_basic< Context >
Implementation of XML parser (core engine).
Template Parameters
Context Context (internal state) of processing.
Definition at line 30 of file xml_parser_basic.h.
Member Typedef Documentation
template<class Context > typedef xml_instruction_processor<Context> middleware::xml::impl::xml_parser_basic< Context >::instruction_processor private
Definition at line 55 of file xml_parser_basic.h.
Member Enumeration Documentation
template<class Context > enum middleware::xml::impl::xml_parser_basic::status_t private
Internal status used in traversing.
Enumerator
ok
All OK.
stay
All OK, stay on current nesting level.
err
Error.
Definition at line 59 of file xml_parser_basic.h.
Member Function Documentation
template<class Context > static void middleware::xml::impl::xml_parser_basic< Context >::clear_buffer (Context & c) inline static private
Definition at line 666 of file xml_parser_basic.h.
Referenced by middleware::xml::impl::xml_parser_basic< Context >::end_tag::at_tag().
template<class Context > static bool middleware::xml::impl::xml_parser_basic< Context >::compare_name (Context & c) inline static private
Definition at line 661 of file xml_parser_basic.h.
Referenced by middleware::xml::impl::xml_parser_basic< Context >::end_tag::at_tag().
template<class Context > static void middleware::xml::impl::xml_parser_basic< Context >::dump_name (Context & c) inline static private
Definition at line 655 of file xml_parser_basic.h.
Referenced by middleware::xml::impl::xml_parser_basic< Context >::start_tag::at_tag(), and middleware::xml::impl::xml_parser_basic< Context >::attributes::at_tag().
template<class Context > static void middleware::xml::impl::xml_parser_basic< Context >::dump_value (Context & c) inline static private
Definition at line 671 of file xml_parser_basic.h.
Referenced by middleware::xml::impl::xml_parser_basic< Context >::attributes::at_content(), and middleware::xml::impl::xml_parser_basic< Context >::any::at_opening_angle_bracket().
template<class Context > static status_t middleware::xml::impl::xml_parser_basic< Context >::input_malformed (Context & c, code_point rotten, xml_error_detail::value_type error_detail = xml_error_detail::no_details) inline static private
Definition at line 678 of file xml_parser_basic.h.
References middleware::xml::impl::xml_parser_basic< Context >::err, and middleware::xml::xml_parser_status::input_malformed.
Referenced by middleware::xml::impl::xml_parser_basic< Context >::attributes::at_attributes(), middleware::xml::impl::xml_parser_basic< Context >::root::at_beginning(), middleware::xml::impl::xml_parser_basic< Context >::comment::at_comment(), middleware::xml::impl::xml_parser_basic< Context >::attributes::at_content(), middleware::xml::impl::xml_parser_basic< Context >::content::at_content(), middleware::xml::impl::xml_parser_basic< Context >::CDATA_section::at_content(), middleware::xml::impl::xml_parser_basic< Context >::entity::at_entity(), middleware::xml::impl::xml_parser_basic< Context >::any::at_exclamation_mark(), middleware::xml::impl::xml_parser_basic< Context >::any::at_first_hyphen(), middleware::xml::impl::xml_parser_basic< Context >::CDATA_section::at_first_square_bracket(), middleware::xml::impl::xml_parser_basic< Context >::processing_instruction::at_instruction(), middleware::xml::impl::xml_parser_basic< Context >::root::at_opening_angle_bracket(), middleware::xml::impl::xml_parser_basic< Context >::any::at_opening_angle_bracket(), middleware::xml::impl::xml_parser_basic< Context >::any::at_opening_square_bracket(), middleware::xml::impl::xml_parser_basic< Context >::processing_instruction::at_question_mark(), middleware::xml::impl::xml_parser_basic< Context >::comment::at_second_hyphen(), middleware::xml::impl::xml_parser_basic< Context >::CDATA_section::at_second_square_bracket(), middleware::xml::impl::xml_parser_basic< Context >::start_tag::at_tag(), middleware::xml::impl::xml_parser_basic< Context >::attributes::at_tag(), middleware::xml::impl::xml_parser_basic< Context >::end_tag::at_tag(), middleware::xml::impl::xml_parser_basic< Context >::start_tag::at_tag_closing_slash(), middleware::xml::impl::xml_parser_basic< Context >::attributes::at_tag_equals(), and middleware::xml::impl::xml_parser_basic< Context >::xml_declaration::at_xml_declaration().
template<class Context > static status_t middleware::xml::impl::xml_parser_basic< Context >::internal_error (Context & c, xml_error_detail::value_type error_detail) inline static private
Definition at line 686 of file xml_parser_basic.h.
References middleware::xml::impl::xml_parser_basic< Context >::err, and middleware::xml::xml_parser_status::internal_error.
Referenced by middleware::xml::impl::xml_parser_basic< Context >::attributes::at_attributes(), middleware::xml::impl::xml_parser_basic< Context >::root::at_beginning(), middleware::xml::impl::xml_parser_basic< Context >::comment::at_comment(), middleware::xml::impl::xml_parser_basic< Context >::attributes::at_content(), middleware::xml::impl::xml_parser_basic< Context >::content::at_content(), middleware::xml::impl::xml_parser_basic< Context >::CDATA_section::at_content(), middleware::xml::impl::xml_parser_basic< Context >::entity::at_entity(), middleware::xml::impl::xml_parser_basic< Context >::processing_instruction::at_instruction(), middleware::xml::impl::xml_parser_basic< Context >::CDATA_section::at_second_square_bracket(), middleware::xml::impl::xml_parser_basic< Context >::start_tag::at_tag(), middleware::xml::impl::xml_parser_basic< Context >::attributes::at_tag(), middleware::xml::impl::xml_parser_basic< Context >::end_tag::at_tag(), middleware::xml::impl::xml_parser_basic< Context >::attributes::at_tag_equals(), middleware::xml::impl::xml_parser_basic< Context >::xml_declaration::at_xml_declaration(), middleware::xml::impl::xml_parser_basic< Context >::parse(), and middleware::xml::impl::xml_parser_basic< Context >::content::skip_indentation().
template<class Context > void middleware::xml::impl::xml_parser_basic< Context >::parse (Context & context) inline
Performs parsing, operating on data contained in context.
Parameters
context Internal state of computations.
Definition at line 37 of file xml_parser_basic.h.
References middleware::xml::impl::xml_parser_basic< Context >::root::at_beginning(), middleware::xml::impl::xml_parser_basic< Context >::internal_error(), middleware::xml::impl::xml_error_detail::memory_allocation_failed, and middleware::xml::impl::xml_error_detail::no_details.
template<class Context > static void middleware::xml::impl::xml_parser_basic< Context >::pop_node (Context & c) inline static private
Definition at line 650 of file xml_parser_basic.h.
Referenced by middleware::xml::impl::xml_parser_basic< Context >::attributes::at_content(), middleware::xml::impl::xml_parser_basic< Context >::end_tag::at_tag(), and middleware::xml::impl::xml_parser_basic< Context >::start_tag::at_tag_closing_slash().
template<class Context > static void middleware::xml::impl::xml_parser_basic< Context >::push_node (Context & c, xml_node_type::value_type const t, code_point const p) inline static private
Definition at line 639 of file xml_parser_basic.h.
Referenced by middleware::xml::impl::xml_parser_basic< Context >::attributes::at_attributes(), middleware::xml::impl::xml_parser_basic< Context >::root::at_opening_angle_bracket(), and middleware::xml::impl::xml_parser_basic< Context >::any::at_opening_angle_bracket().
The documentation for this class was generated from the following file:
includes/middleware/xml/impl/xml_parser_basic.h