#   @b Project: Wump
#   @file        paths_custom.inc
#   @author      Szymon Gutaj
#   @brief       Defines custom paths, if needed by user. Active if make invoked with PATHS_CUSTOM=Yes. Please add this file to "ignore list" in your local copy.
#   @date        30-03-2011
#   @version     0.1
#   @b History:
#    - 30-03-2011
#      - sgutaj
#        - Initial creation

# At home
TESTS_DIR_PYTHON:=C:/Apps/Python/
TESTS_DIR_CYGWIN:=C:/MinGW/msys/1.0/bin/
TESTS_DIR_GCC:=C:/MinGW/bin/
