xml_parser: middleware::xml::xml_node_basic< Encoding > Class Template Reference
middleware::xml::xml_node_basic< Encoding > Class Template Reference
#include <xml_node_basic.h>
Public Types
typedef xml_node_basic type
Returns self type.
typedef Encoding encoding
Returns supported encodings list (for internal use)
typedef std::basic_string
< typename Encoding::type > value_type
Returns type of textual node members.
Public Types inherited from middleware::xml::impl::xml_node_tree< xml_node_basic< Encoding > >
typedef xml_node_tree type
Returns self.
typedef xml_node_basic< Encoding > value_type
Returns value type (payload).
typedef std::deque< value_type > children_type
Returns children type (collection).
Public Member Functions
xml_node_basic ()
xml_node_basic (xml_node_type::value_type node_type)
xml_node_basic (xml_node_basic const &original)
xml_node_basic & operator= (xml_node_basic rhs)
bool operator== (xml_node_basic const &rhs) const
bool operator!= (xml_node_basic const &rhs) const
void swap (xml_node_basic &node) throw ()
value_type const & get_name () const
value_type const & get_value () const
xml_node_type get_type () const
xml_node_type & set_type ()
void set_type (xml_node_type::value_type node_type)
value_type & set_name ()
void set_name (value_type const &name)
value_type & set_value ()
void set_value (value_type const &value)
Public Member Functions inherited from middleware::xml::impl::xml_node_tree< xml_node_basic< Encoding > >
xml_node_tree ()
xml_node_tree (xml_node_tree const &original)
~xml_node_tree ()
xml_node_tree & operator= (xml_node_tree rhs)
bool operator== (xml_node_tree const &rhs) const
void swap (xml_node_tree &node) throw ()
children_type const & get_children () const
children_type & set_children ()
Private Types
typedef impl::xml_node_tree
< xml_node_basic< Encoding > > base
Private Attributes
xml_node_type node_type
value_type name
value_type value
Detailed Description
template<class Encoding>
class middleware::xml::xml_node_basic< Encoding >
Basic XML node type. Holds elemental XML data in a tree structure.
Template Parameters
Encoding Encoding of node's textual content.
Definition at line 29 of file xml_node_basic.h.
Member Typedef Documentation
template<class Encoding > typedef impl::xml_node_tree<xml_node_basic<Encoding> > middleware::xml::xml_node_basic< Encoding >::base private
Definition at line 38 of file xml_node_basic.h.
template<class Encoding > typedef Encoding middleware::xml::xml_node_basic< Encoding >::encoding
Returns supported encodings list (for internal use)
Definition at line 34 of file xml_node_basic.h.
template<class Encoding > typedef xml_node_basic middleware::xml::xml_node_basic< Encoding >::type
Returns self type.
Definition at line 33 of file xml_node_basic.h.
template<class Encoding > typedef std::basic_string<typename Encoding::type> middleware::xml::xml_node_basic< Encoding >::value_type
Returns type of textual node members.
Definition at line 35 of file xml_node_basic.h.
Constructor & Destructor Documentation
template<class Encoding > middleware::xml::xml_node_basic< Encoding >::xml_node_basic () inline
Default constructor.
Definition at line 44 of file xml_node_basic.h.
template<class Encoding > middleware::xml::xml_node_basic< Encoding >::xml_node_basic (xml_node_type::value_type node_type) inline explicit
Constructor taking initial node type.
Parameters
node_type Initial node type.
Definition at line 56 of file xml_node_basic.h.
template<class Encoding > middleware::xml::xml_node_basic< Encoding >::xml_node_basic (xml_node_basic< Encoding > const & original) inline
Copy constructor.
Parameters
original Source node.
Definition at line 68 of file xml_node_basic.h.
References middleware::xml::xml_node_basic< Encoding >::name, middleware::xml::impl::xml_node_tree< xml_node_basic< Encoding > >::operator=(), and middleware::xml::xml_node_basic< Encoding >::value.
Member Function Documentation
template<class Encoding > value_type const& middleware::xml::xml_node_basic< Encoding >::get_name () const inline
Node's metadata getter.
Returns
Returns node's metadata.
Definition at line 132 of file xml_node_basic.h.
References middleware::xml::xml_node_basic< Encoding >::name.
template<class Encoding > xml_node_type middleware::xml::xml_node_basic< Encoding >::get_type () const inline
Node's type (root/attribute/element..etc) getter.
Returns
Returns node's type.
Definition at line 150 of file xml_node_basic.h.
References middleware::xml::xml_node_basic< Encoding >::node_type.
template<class Encoding > value_type const& middleware::xml::xml_node_basic< Encoding >::get_value () const inline
Node's data getter.
Returns
Returns node's value.
Definition at line 141 of file xml_node_basic.h.
References middleware::xml::xml_node_basic< Encoding >::value.
template<class Encoding > bool middleware::xml::xml_node_basic< Encoding >::operator!= (xml_node_basic< Encoding > const & rhs) const inline
Different operator.
Parameters
rhs Right hand side comparison argument.
Returns
Returns true if any of node members' values different.
Definition at line 108 of file xml_node_basic.h.
References middleware::xml::xml_node_basic< Encoding >::operator==().
template<class Encoding > xml_node_basic& middleware::xml::xml_node_basic< Encoding >::operator= (xml_node_basic< Encoding > rhs) inline
Assign operator.
Parameters
rhs Source node.
Returns
Reference to self.
Definition at line 84 of file xml_node_basic.h.
References middleware::xml::xml_node_basic< Encoding >::swap().
template<class Encoding > bool middleware::xml::xml_node_basic< Encoding >::operator== (xml_node_basic< Encoding > const & rhs) const inline
Equals operator.
Parameters
rhs Right hand side comparison argument.
Returns
Returns true if all node members' values equal.
Definition at line 95 of file xml_node_basic.h.
References middleware::xml::xml_node_basic< Encoding >::name, middleware::xml::xml_node_basic< Encoding >::node_type, middleware::xml::impl::xml_node_tree< xml_node_basic< Encoding > >::operator==(), middleware::xml::xml_node_type::value, and middleware::xml::xml_node_basic< Encoding >::value.
Referenced by middleware::xml::xml_node_basic< Encoding >::operator!=().
template<class Encoding > value_type& middleware::xml::xml_node_basic< Encoding >::set_name () inline
Node's metadata setter.
Returns
Reference to node's name.
Definition at line 173 of file xml_node_basic.h.
References middleware::xml::xml_node_basic< Encoding >::name.
template<class Encoding > void middleware::xml::xml_node_basic< Encoding >::set_name (value_type const & name) inline
Node's metadata setter.
Definition at line 181 of file xml_node_basic.h.
References middleware::xml::xml_node_basic< Encoding >::name.
template<class Encoding > xml_node_type& middleware::xml::xml_node_basic< Encoding >::set_type () inline
Node's type setter.
Returns
Reference to node's type.
Definition at line 159 of file xml_node_basic.h.
References middleware::xml::xml_node_basic< Encoding >::node_type.
template<class Encoding > void middleware::xml::xml_node_basic< Encoding >::set_type (xml_node_type::value_type node_type) inline
Definition at line 164 of file xml_node_basic.h.
References middleware::xml::xml_node_basic< Encoding >::node_type.
template<class Encoding > value_type& middleware::xml::xml_node_basic< Encoding >::set_value () inline
Node's data setter.
Returns
Reference to node's value.
Definition at line 190 of file xml_node_basic.h.
References middleware::xml::xml_node_basic< Encoding >::value.
template<class Encoding > void middleware::xml::xml_node_basic< Encoding >::set_value (value_type const & value) inline
Node's data setter.
Definition at line 198 of file xml_node_basic.h.
References middleware::xml::xml_node_basic< Encoding >::value.
template<class Encoding > void middleware::xml::xml_node_basic< Encoding >::swap (xml_node_basic< Encoding > & node) throw () inline
Exception-safe swap function.
Parameters
node Node to be swapped with.
Definition at line 119 of file xml_node_basic.h.
References middleware::xml::xml_node_basic< Encoding >::name, middleware::xml::xml_node_basic< Encoding >::node_type, middleware::xml::impl::xml_node_tree< xml_node_basic< Encoding > >::swap(), and middleware::xml::xml_node_basic< Encoding >::value.
Referenced by middleware::xml::xml_node_basic< Encoding >::operator=().
Member Data Documentation
template<class Encoding > value_type middleware::xml::xml_node_basic< Encoding >::name private
Definition at line 205 of file xml_node_basic.h.
Referenced by middleware::xml::xml_node_basic< Encoding >::get_name(), middleware::xml::xml_node_basic< Encoding >::operator==(), middleware::xml::xml_node_basic< Encoding >::set_name(), middleware::xml::xml_node_basic< Encoding >::swap(), and middleware::xml::xml_node_basic< Encoding >::xml_node_basic().
template<class Encoding > xml_node_type middleware::xml::xml_node_basic< Encoding >::node_type private
Definition at line 204 of file xml_node_basic.h.
Referenced by middleware::xml::xml_node_basic< Encoding >::get_type(), middleware::xml::xml_node_basic< Encoding >::operator==(), middleware::xml::xml_node_basic< Encoding >::set_type(), and middleware::xml::xml_node_basic< Encoding >::swap().
template<class Encoding > value_type middleware::xml::xml_node_basic< Encoding >::value private
Definition at line 206 of file xml_node_basic.h.
Referenced by middleware::xml::xml_node_basic< Encoding >::get_value(), middleware::xml::xml_node_basic< Encoding >::operator==(), middleware::xml::xml_node_basic< Encoding >::set_value(), middleware::xml::xml_node_basic< Encoding >::swap(), and middleware::xml::xml_node_basic< Encoding >::xml_node_basic().
The documentation for this class was generated from the following file:
includes/middleware/xml/xml_node_basic.h