xml_parser: middleware::xml::impl::local::xml_decoder_selector_optimized< XmlEncodingsCount, XmlEncodings, XmlStream > Class Template Reference
middleware::xml::impl::local::xml_decoder_selector_optimized< XmlEncodingsCount, XmlEncodings, XmlStream > Class Template Reference
#include <xml_decoder_selector.h>
Classes
class register_decoding_function
struct xml_decl_less
Public Types
typedef xml_decoder< XmlStream > decoder_type
Type of decoder returned by decoder selector.
Public Member Functions
xml_decoder_selector_optimized ()
decoder_type select (XmlStream &stream) const
Private Types
typedef decode_function
< XmlStream >::type decode_function
typedef std::pair
< xml_decl_type const
*,decode_function > xml_decl_to_decoding_function
Private Member Functions
decode_function fetch_decoding_function (XmlStream &stream) const
Private Attributes
xml_decl_to_decoding_function decoding_functions_map [XmlEncodingsCount]
Detailed Description
template<int XmlEncodingsCount, class XmlEncodings, class XmlStream>
class middleware::xml::impl::local::xml_decoder_selector_optimized< XmlEncodingsCount, XmlEncodings, XmlStream >
General version of selector if many encodings possible.
Template Parameters
XmlEncodingsCount Count of supported encodings.
XmlEncodings List of supported encodings.
XmlStream Type of input stream.
Definition at line 47 of file xml_decoder_selector.h.
Member Typedef Documentation
template<int XmlEncodingsCount, class XmlEncodings , class XmlStream > typedef decode_function<XmlStream>::type middleware::xml::impl::local::xml_decoder_selector_optimized< XmlEncodingsCount, XmlEncodings, XmlStream >::decode_function private
Definition at line 49 of file xml_decoder_selector.h.
template<int XmlEncodingsCount, class XmlEncodings , class XmlStream > typedef xml_decoder<XmlStream> middleware::xml::impl::local::xml_decoder_selector_optimized< XmlEncodingsCount, XmlEncodings, XmlStream >::decoder_type
Type of decoder returned by decoder selector.
Definition at line 98 of file xml_decoder_selector.h.
template<int XmlEncodingsCount, class XmlEncodings , class XmlStream > typedef std::pair< xml_decl_type const* ,decode_function > middleware::xml::impl::local::xml_decoder_selector_optimized< XmlEncodingsCount, XmlEncodings, XmlStream >::xml_decl_to_decoding_function private
Definition at line 54 of file xml_decoder_selector.h.
Constructor & Destructor Documentation
template<int XmlEncodingsCount, class XmlEncodings , class XmlStream > middleware::xml::impl::local::xml_decoder_selector_optimized< XmlEncodingsCount, XmlEncodings, XmlStream >::xml_decoder_selector_optimized () inline
Constructor: fill and sort the decoders' map entries
Definition at line 104 of file xml_decoder_selector.h.
References middleware::xml::impl::local::xml_decoder_selector_optimized< XmlEncodingsCount, XmlEncodings, XmlStream >::decoding_functions_map.
Member Function Documentation
template<int XmlEncodingsCount, class XmlEncodings , class XmlStream > decode_function middleware::xml::impl::local::xml_decoder_selector_optimized< XmlEncodingsCount, XmlEncodings, XmlStream >::fetch_decoding_function (XmlStream & stream) const inline private
Definition at line 126 of file xml_decoder_selector.h.
References middleware::xml::impl::local::xml_decoder_selector_optimized< XmlEncodingsCount, XmlEncodings, XmlStream >::decoding_functions_map.
Referenced by middleware::xml::impl::local::xml_decoder_selector_optimized< XmlEncodingsCount, XmlEncodings, XmlStream >::select().
template<int XmlEncodingsCount, class XmlEncodings , class XmlStream > decoder_type middleware::xml::impl::local::xml_decoder_selector_optimized< XmlEncodingsCount, XmlEncodings, XmlStream >::select (XmlStream & stream) const inline
Returns the decoder of detected encoding (actual implementation).
Parameters
stream Input XML stream.
Returns
Detected decoder (default if not found an exact match).
Definition at line 120 of file xml_decoder_selector.h.
References middleware::xml::impl::local::xml_decoder_selector_optimized< XmlEncodingsCount, XmlEncodings, XmlStream >::fetch_decoding_function().
Referenced by middleware::xml::impl::xml_decoder_selector< XmlEncodings, XmlStream >::select().
Member Data Documentation
template<int XmlEncodingsCount, class XmlEncodings , class XmlStream > xml_decl_to_decoding_function middleware::xml::impl::local::xml_decoder_selector_optimized< XmlEncodingsCount, XmlEncodings, XmlStream >::decoding_functions_map[XmlEncodingsCount] private
Definition at line 152 of file xml_decoder_selector.h.
Referenced by middleware::xml::impl::local::xml_decoder_selector_optimized< XmlEncodingsCount, XmlEncodings, XmlStream >::fetch_decoding_function(), and middleware::xml::impl::local::xml_decoder_selector_optimized< XmlEncodingsCount, XmlEncodings, XmlStream >::xml_decoder_selector_optimized().
The documentation for this class was generated from the following file:
includes/middleware/xml/impl/xml_decoder_selector.h