xml_parser: middleware::xml::impl::xml_instruction_processor< Context > Class Template Reference
middleware::xml::impl::xml_instruction_processor< Context > Class Template Reference
#include <xml_instruction_processor.h>
Static Public Member Functions
static bool process_instruction (Context &c)
static bool process_entity_reference (Context &c)
Private Types
typedef fwd::rt::assoc_vector
< xml_buffer_raw_utf,
code_point > entities_t
Static Private Member Functions
template<class In , class OutStream >
static bool to_entity (In &in, OutStream &out)
template<class In , class OutStream >
static bool to_numeral (In &in, OutStream &out)
Static Private Attributes
static entities_t entities
Detailed Description
template<class Context>
class middleware::xml::impl::xml_instruction_processor< Context >
Processes XML instructions, returning OK/NOK status.
Template Parameters
Context Type of internal state of parser.
Definition at line 27 of file xml_instruction_processor.h.
Member Typedef Documentation
template<class Context> typedef fwd::rt::assoc_vector<xml_buffer_raw_utf, code_point> middleware::xml::impl::xml_instruction_processor< Context >::entities_t private
Definition at line 59 of file xml_instruction_processor.h.
Member Function Documentation
template<class Context> static bool middleware::xml::impl::xml_instruction_processor< Context >::process_entity_reference (Context & c) inline static
Processes entity reference.
Parameters
c Input data/context.
Returns
Returns true if processing OK.
Definition at line 47 of file xml_instruction_processor.h.
References middleware::xml::impl::xml_instruction_processor< Context >::to_entity(), and middleware::xml::impl::xml_instruction_processor< Context >::to_numeral().
Referenced by middleware::xml::impl::xml_parser_basic< Context >::entity::at_entity().
template<class Context> static bool middleware::xml::impl::xml_instruction_processor< Context >::process_instruction (Context & c) inline static
Processes instruction.
Parameters
c Input data/context.
Returns
Returns true if processing OK.
Definition at line 35 of file xml_instruction_processor.h.
Referenced by middleware::xml::impl::xml_parser_basic< Context >::processing_instruction::at_question_mark().
template<class Context> template<class In , class OutStream > static bool middleware::xml::impl::xml_instruction_processor< Context >::to_entity (In & in, OutStream & out) inline static private
Definition at line 62 of file xml_instruction_processor.h.
References middleware::xml::impl::xml_instruction_processor< Context >::entities.
Referenced by middleware::xml::impl::xml_instruction_processor< Context >::process_entity_reference().
template<class Context> template<class In , class OutStream > static bool middleware::xml::impl::xml_instruction_processor< Context >::to_numeral (In & in, OutStream & out) inline static private
Definition at line 70 of file xml_instruction_processor.h.
Referenced by middleware::xml::impl::xml_instruction_processor< Context >::process_entity_reference().
Member Data Documentation
template<class Context> xml_instruction_processor< Context >::entities_t middleware::xml::impl::xml_instruction_processor< Context >::entities static private
Initial value:
=
    xml_instruction_processor<Context>::entities_t()(r2e("amp"),'&')(r2e("apos"),'\'')(r2e("gt"),'>')(r2e("lt"),'<')(r2e("quot"),'\"').sort()
Definition at line 92 of file xml_instruction_processor.h.
Referenced by middleware::xml::impl::xml_instruction_processor< Context >::to_entity().
The documentation for this class was generated from the following file:
includes/middleware/xml/impl/xml_instruction_processor.h