xml_parser: middleware::xml::impl::xml_parser_basic< Context >::content Struct Reference
middleware::xml::impl::xml_parser_basic< Context >::content Struct Reference
Process content.
Static Public Member Functions
static code_point normalise_newline (Context &c, code_point const pp)
Normalise newline to LFLF.
static code_point skip_indentation (Context &c)
Skip white space after newline.
static status_t at_content (Context &c)
At "<Name>Value".
Detailed Description
template<class Context>
struct middleware::xml::impl::xml_parser_basic< Context >::content
Process content.
Definition at line 434 of file xml_parser_basic.h.
Member Function Documentation
template<class Context > static status_t middleware::xml::impl::xml_parser_basic< Context >::content::at_content (Context & c) inline static
At "<Name>Value".
Definition at line 463 of file xml_parser_basic.h.
References middleware::xml::impl::xml_parser_basic< Context >::entity::at_entity(), middleware::xml::impl::xml_parser_basic< Context >::any::at_opening_angle_bracket(), middleware::xml::impl::xml_parser_basic< Context >::input_malformed(), middleware::xml::impl::xml_parser_basic< Context >::internal_error(), middleware::xml::is_root(), middleware::xml::impl::xml_parser_basic< Context >::content::normalise_newline(), middleware::xml::impl::xml_parser_basic< Context >::ok, middleware::xml::impl::xml_parser_basic< Context >::content::skip_indentation(), middleware::xml::impl::xml_parser_basic< Context >::stay, and middleware::xml::impl::xml_error_detail::unexpected_control_flow.
Referenced by middleware::xml::impl::xml_parser_basic< Context >::root::at_beginning().
template<class Context > static code_point middleware::xml::impl::xml_parser_basic< Context >::content::normalise_newline (Context & c, code_point const pp) inline static
Normalise newline to LFLF.
Definition at line 437 of file xml_parser_basic.h.
Referenced by middleware::xml::impl::xml_parser_basic< Context >::content::at_content().
template<class Context > static code_point middleware::xml::impl::xml_parser_basic< Context >::content::skip_indentation (Context & c) inline static
Skip white space after newline.
Definition at line 446 of file xml_parser_basic.h.
References middleware::xml::impl::xml_parser_basic< Context >::internal_error(), and middleware::xml::impl::xml_error_detail::unexpected_control_flow.
Referenced by middleware::xml::impl::xml_parser_basic< Context >::content::at_content().
The documentation for this struct was generated from the following file:
includes/middleware/xml/impl/xml_parser_basic.h