xml_parser: middleware::utils::rt::assoc_vector< Key, T, Compare, Alloc > Class Template Reference
middleware::utils::rt::assoc_vector< Key, T, Compare, Alloc > Class Template Reference
#include <assoc_vector.h>
Classes
class value_compare
Public Types
typedef Key key_type
typedef T mapped_type
typedef Compare key_compare
typedef Alloc allocator_type
typedef std::pair< Key, T > value_type
typedef vector_t::iterator iterator
typedef vector_t::const_iterator const_iterator
typedef vector_t::pointer pointer
typedef vector_t::const_pointer const_pointer
typedef vector_t::reference reference
typedef vector_t::const_reference const_reference
typedef vector_t::size_type size_type
Public Member Functions
assoc_vector ()
void swap (assoc_vector v)
assoc_vector & operator= (assoc_vector const &v)
iterator find (key_type const &key)
iterator begin ()
iterator end ()
bool empty () const
void reserve (size_type size)
std::pair< iterator, bool > insert (value_type const &value)
assoc_vector & operator() (key_type const &key, mapped_type const &t)
assoc_vector & sort ()
Private Types
typedef std::vector< std::pair
< Key, T >, Alloc > vector_t
Private Attributes
vector_t v
Detailed Description
template<class Key, class T, class Compare = std::less<Key>, class Alloc = std::allocator<T>>
class middleware::utils::rt::assoc_vector< Key, T, Compare, Alloc >
Definition at line 26 of file assoc_vector.h.
Member Typedef Documentation
template<class Key , class T , class Compare = std::less<Key>, class Alloc = std::allocator<T>> typedef Alloc middleware::utils::rt::assoc_vector< Key, T, Compare, Alloc >::allocator_type
Definition at line 34 of file assoc_vector.h.
template<class Key , class T , class Compare = std::less<Key>, class Alloc = std::allocator<T>> typedef vector_t::const_iterator middleware::utils::rt::assoc_vector< Key, T, Compare, Alloc >::const_iterator
Definition at line 38 of file assoc_vector.h.
template<class Key , class T , class Compare = std::less<Key>, class Alloc = std::allocator<T>> typedef vector_t::const_pointer middleware::utils::rt::assoc_vector< Key, T, Compare, Alloc >::const_pointer
Definition at line 41 of file assoc_vector.h.
template<class Key , class T , class Compare = std::less<Key>, class Alloc = std::allocator<T>> typedef vector_t::const_reference middleware::utils::rt::assoc_vector< Key, T, Compare, Alloc >::const_reference
Definition at line 44 of file assoc_vector.h.
template<class Key , class T , class Compare = std::less<Key>, class Alloc = std::allocator<T>> typedef vector_t::iterator middleware::utils::rt::assoc_vector< Key, T, Compare, Alloc >::iterator
Definition at line 37 of file assoc_vector.h.
template<class Key , class T , class Compare = std::less<Key>, class Alloc = std::allocator<T>> typedef Compare middleware::utils::rt::assoc_vector< Key, T, Compare, Alloc >::key_compare
Definition at line 33 of file assoc_vector.h.
template<class Key , class T , class Compare = std::less<Key>, class Alloc = std::allocator<T>> typedef Key middleware::utils::rt::assoc_vector< Key, T, Compare, Alloc >::key_type
Definition at line 31 of file assoc_vector.h.
template<class Key , class T , class Compare = std::less<Key>, class Alloc = std::allocator<T>> typedef T middleware::utils::rt::assoc_vector< Key, T, Compare, Alloc >::mapped_type
Definition at line 32 of file assoc_vector.h.
template<class Key , class T , class Compare = std::less<Key>, class Alloc = std::allocator<T>> typedef vector_t::pointer middleware::utils::rt::assoc_vector< Key, T, Compare, Alloc >::pointer
Definition at line 40 of file assoc_vector.h.
template<class Key , class T , class Compare = std::less<Key>, class Alloc = std::allocator<T>> typedef vector_t::reference middleware::utils::rt::assoc_vector< Key, T, Compare, Alloc >::reference
Definition at line 43 of file assoc_vector.h.
template<class Key , class T , class Compare = std::less<Key>, class Alloc = std::allocator<T>> typedef vector_t::size_type middleware::utils::rt::assoc_vector< Key, T, Compare, Alloc >::size_type
Definition at line 46 of file assoc_vector.h.
template<class Key , class T , class Compare = std::less<Key>, class Alloc = std::allocator<T>> typedef std::pair<Key, T> middleware::utils::rt::assoc_vector< Key, T, Compare, Alloc >::value_type
Definition at line 35 of file assoc_vector.h.
template<class Key , class T , class Compare = std::less<Key>, class Alloc = std::allocator<T>> typedef std::vector<std::pair<Key, T>, Alloc> middleware::utils::rt::assoc_vector< Key, T, Compare, Alloc >::vector_t private
Definition at line 28 of file assoc_vector.h.
Constructor & Destructor Documentation
template<class Key , class T , class Compare = std::less<Key>, class Alloc = std::allocator<T>> middleware::utils::rt::assoc_vector< Key, T, Compare, Alloc >::assoc_vector () inline
Definition at line 60 of file assoc_vector.h.
Member Function Documentation
template<class Key , class T , class Compare = std::less<Key>, class Alloc = std::allocator<T>> iterator middleware::utils::rt::assoc_vector< Key, T, Compare, Alloc >::begin () inline
Definition at line 87 of file assoc_vector.h.
References middleware::utils::rt::assoc_vector< Key, T, Compare, Alloc >::v.
template<class Key , class T , class Compare = std::less<Key>, class Alloc = std::allocator<T>> bool middleware::utils::rt::assoc_vector< Key, T, Compare, Alloc >::empty () const inline
Definition at line 97 of file assoc_vector.h.
References middleware::utils::rt::assoc_vector< Key, T, Compare, Alloc >::v.
template<class Key , class T , class Compare = std::less<Key>, class Alloc = std::allocator<T>> iterator middleware::utils::rt::assoc_vector< Key, T, Compare, Alloc >::end () inline
Definition at line 92 of file assoc_vector.h.
References middleware::utils::rt::assoc_vector< Key, T, Compare, Alloc >::v.
template<class Key , class T , class Compare = std::less<Key>, class Alloc = std::allocator<T>> iterator middleware::utils::rt::assoc_vector< Key, T, Compare, Alloc >::find (key_type const & key) inline
Definition at line 75 of file assoc_vector.h.
References middleware::utils::rt::assoc_vector< Key, T, Compare, Alloc >::v.
Referenced by middleware::utils::rt::assoc_vector< Key, T, Compare, Alloc >::insert().
template<class Key , class T , class Compare = std::less<Key>, class Alloc = std::allocator<T>> std::pair<iterator, bool> middleware::utils::rt::assoc_vector< Key, T, Compare, Alloc >::insert (value_type const & value) inline
Definition at line 107 of file assoc_vector.h.
References middleware::utils::rt::assoc_vector< Key, T, Compare, Alloc >::find(), and middleware::utils::rt::assoc_vector< Key, T, Compare, Alloc >::v.
template<class Key , class T , class Compare = std::less<Key>, class Alloc = std::allocator<T>> assoc_vector& middleware::utils::rt::assoc_vector< Key, T, Compare, Alloc >::operator() (key_type const & key, mapped_type const & t) inline
Definition at line 122 of file assoc_vector.h.
References middleware::utils::rt::assoc_vector< Key, T, Compare, Alloc >::v.
template<class Key , class T , class Compare = std::less<Key>, class Alloc = std::allocator<T>> assoc_vector& middleware::utils::rt::assoc_vector< Key, T, Compare, Alloc >::operator= (assoc_vector< Key, T, Compare, Alloc > const & v) inline
Definition at line 69 of file assoc_vector.h.
References middleware::utils::rt::assoc_vector< Key, T, Compare, Alloc >::swap().
template<class Key , class T , class Compare = std::less<Key>, class Alloc = std::allocator<T>> void middleware::utils::rt::assoc_vector< Key, T, Compare, Alloc >::reserve (size_type size) inline
Definition at line 102 of file assoc_vector.h.
References middleware::utils::rt::assoc_vector< Key, T, Compare, Alloc >::v.
template<class Key , class T , class Compare = std::less<Key>, class Alloc = std::allocator<T>> assoc_vector& middleware::utils::rt::assoc_vector< Key, T, Compare, Alloc >::sort () inline
Definition at line 128 of file assoc_vector.h.
References middleware::utils::rt::assoc_vector< Key, T, Compare, Alloc >::v.
template<class Key , class T , class Compare = std::less<Key>, class Alloc = std::allocator<T>> void middleware::utils::rt::assoc_vector< Key, T, Compare, Alloc >::swap (assoc_vector< Key, T, Compare, Alloc > v) inline
Definition at line 64 of file assoc_vector.h.
References middleware::utils::rt::assoc_vector< Key, T, Compare, Alloc >::swap().
Referenced by middleware::utils::rt::assoc_vector< Key, T, Compare, Alloc >::operator=(), and middleware::utils::rt::assoc_vector< Key, T, Compare, Alloc >::swap().
Member Data Documentation
template<class Key , class T , class Compare = std::less<Key>, class Alloc = std::allocator<T>> vector_t middleware::utils::rt::assoc_vector< Key, T, Compare, Alloc >::v private
Definition at line 135 of file assoc_vector.h.
Referenced by middleware::utils::rt::assoc_vector< Key, T, Compare, Alloc >::begin(), middleware::utils::rt::assoc_vector< Key, T, Compare, Alloc >::empty(), middleware::utils::rt::assoc_vector< Key, T, Compare, Alloc >::end(), middleware::utils::rt::assoc_vector< Key, T, Compare, Alloc >::find(), middleware::utils::rt::assoc_vector< Key, T, Compare, Alloc >::insert(), middleware::utils::rt::assoc_vector< Key, T, Compare, Alloc >::operator()(), middleware::utils::rt::assoc_vector< Key, T, Compare, Alloc >::reserve(), and middleware::utils::rt::assoc_vector< Key, T, Compare, Alloc >::sort().
The documentation for this class was generated from the following file:
includes/middleware/utils/rt/assoc_vector.h